#include "IncludeFiles.h"

static bool setOnce = true;
 bool setOncew = true;
static ImVec4 menuPostion = { 60,60, 450, 150 };
static ImVec4 selctedMenuPostion = { 150, 0, 450, 450 };
static ImVec2 selctedMenuPostionUpdated;

struct Model { std::string ModelHash; std::string ModelName; int ID; };
std::vector<Model> PedModels{

	{"a_c_cat_01", "Cat", 0 },
	{"a_c_boar", "Boar", 0 },
	{"a_c_cormorant", "Cormorant", 0 },
	{"a_c_cow", "Cow", 0 },
	{"a_c_coyote", "Coyote", 0 },
	{"a_c_crow", "Crow", 0 },
	{"a_c_deer", "Deer", 0 },
	{"a_c_fish", "Fish", 0 },
	{"a_c_dolphin", "Dolphin", 0 },
	{"a_c_sharkhammer", "Hammer shark", 0 },
	{"a_c_hen", "Hen", 0 },
	{"a_c_humpback", "Humback", 0 },
	{"a_c_husky", "Husky", 0 },
	{"a_c_killerwhale", "Killer whale", 0 },
	{"a_c_mtlion", "M.T. Loin", 0 },
	{"a_c_pig", "Pig", 0 },
	{"a_c_pigeon", "Pigeon", 0 },
	{"a_c_poodle", "Poodle", 0 },
	{"a_c_pug", "Pug", 0 },
	{"a_c_rabbit_01", "Rabbit", 0 },
	{"a_c_rat", "Rat", 0 },
	{"a_c_retriever", "Retriever", 0 },
	{"a_c_rhesus", "Rhesus", 0 },
	{"a_c_rottweiler", "Rottweiler", 0 },
	{"a_c_seagull", "Seagull", 0 },
	{"a_c_shepherd", "Shepherd", 0 },
	{"a_c_stingray", "Stingray", 0 },
	{"a_c_sharktiger", "Tiger shark", 0 },
	{"a_c_westy", "Westy", 0 },
	{"a_f_m_beach_01", "Beach Female", 1},
	{"a_f_m_trampbeac_01", "Beach Tramp Female", 1},
	{"a_f_y_beach_01", "Beach Young Female", 1},
	{"a_f_m_bevhills_01", "Beverly Hills Female", 1},
	{"a_f_m_bevhills_02", "Beverly Hills Female 2", 1},
	{"a_f_y_bevhills_01", "Beverly Hills Young Female", 1},
	{"a_f_y_bevhills_02", "Beverly Hills Young Female 2", 1},
	{"a_f_y_bevhills_03", "Beverly Hills Young Female 3", 1},
	{"a_f_y_bevhills_04", "Beverly Hills Young Female 4", 1},
	{"a_f_m_bodybuild_01", "Bodybuilder Female", 1},
	{"a_f_m_business_02", "Business Female 2", 1},
	{"a_f_y_business_01", "Business Young Female", 1},
	{"a_f_y_business_02", "Business Young Female 2", 1},
	{"a_f_y_business_03", "Business Young Female 3", 1},
	{"a_f_y_business_04", "Business Young Female 4", 1},
	{"a_f_m_downtown_01", "Downtown Female", 1},
	{"a_f_y_scdressy_01", "Dressy Female", 1},
	{"a_f_m_eastsa_01", "East SA Female", 1},
	{"a_f_m_eastsa_02", "East SA Female 2", 1},
	{"a_f_y_eastsa_01", "East SA Young Female", 1},
	{"a_f_y_eastsa_02", "East SA Young Female 2", 1},
	{"a_f_y_eastsa_03", "East SA Young Female 3", 1},
	{"a_f_y_epsilon_01", "Epsilon Female", 1},
	{"a_f_m_fatbla_01", "Fat Black Female", 1},
	{"a_f_m_fatcult_01", "Fat Cult Female", 1},
	{"a_f_m_fatwhite_01", "Fat White Female", 1},
	{"a_f_y_femaleagent", "Female Agent", 1},
	{"a_f_y_fitness_01", "Fitness Female", 1},
	{"a_f_y_fitness_02", "Fitness Female 2", 1},
	{"a_f_y_genhot_01", "General Hot Young Female", 1},
	{"a_f_o_genstreet_01", "General Street Old Female", 1},
	{"a_f_y_gencaspat_01", "Casual Casino Guest", 1},
	{"a_f_y_smartcaspat_01", "Formel Casino Guest", 1},
	{"a_f_y_golfer_01", "Golfer Young Female", 1},
	{"a_f_y_hiker_01", "Hiker Female", 1},
	{"a_f_y_hippie_01", "Hippie Female", 1},
	{"a_f_y_hipster_01", "Hipster Female", 1},
	{"a_f_y_hipster_02", "Hipster Female 2", 1},
	{"a_f_y_hipster_03", "Hipster Female 3", 1},
	{"a_f_y_hipster_04", "Hipster Female 4", 1},
	{"a_f_o_indian_01", "Indian Old Female", 1},
	{"a_f_y_indian_01", "Indian Young Female", 1},
	{"a_f_y_runner_01", "Jogger Female", 1},
	{"a_f_y_juggalo_01", "Juggalo Female", 1},
	{"a_f_m_ktown_01", "Korean Female", 1},
	{"a_f_m_ktown_02", "Korean Female 2", 1},
	{"a_f_o_ktown_01", "Korean Old Female", 1},
	{"a_f_m_prolhost_01", "Prologue Host Female", 1},
	{"a_f_y_rurmeth_01", "Rural Meth Addict Female", 1},
	{"a_f_m_salton_01", "Salton Female", 1},
	{"a_f_o_salton_01", "Salton Old Female", 1},
	{"a_f_y_skater_01", "Skater Female", 1},
	{"a_f_m_skidrow_01", "Skid Row Female", 1},
	{"a_f_m_soucent_01", "South Central Female", 1},
	{"a_f_m_soucent_02", "South Central Female 2", 1},
	{"a_f_m_soucentmc_01", "South Central MC Female", 1},
	{"a_f_o_soucent_01", "South Central Old Female", 1},
	{"a_f_o_soucent_02", "South Central Old Female 2", 1},
	{"a_f_y_soucent_01", "South Central Young Female", 1},
	{"a_f_y_soucent_02", "South Central Young Female 2", 1},
	{"a_f_y_soucent_03", "South Central Young Female 3", 1},
	{"a_f_y_tennis_01", "Tennis Player Female", 1},
	{"a_f_y_topless_01", "Topless", 1},
	{"a_f_m_tourist_01", "Tourist Female", 1},
	{"a_f_y_tourist_01", "Tourist Young Female", 1},
	{"a_f_y_tourist_02", "Tourist Young Female 2", 1},
	{"a_f_m_tramp_01", "Tramp Female", 1},
	{"a_f_y_vinewood_01", "Vinewood Female", 1},
	{"a_f_y_vinewood_02", "Vinewood Female 2", 1},
	{"a_f_y_vinewood_03", "Vinewood Female 3", 1},
	{"a_f_y_vinewood_04", "Vinewood Female 4", 1},
	{"a_f_y_yoga_01", "Yoga Female", 1},
	{"a_f_y_clubcust_01", "Club Customer Female 1", 1},
	{"a_f_y_clubcust_02", "Club Customer Female 2", 1},
	{"a_f_y_clubcust_03", "Club Customer Female 3" , 1},

	{"a_m_m_afriamer_01", "African American Male", 2},
	{ "a_m_m_acult_01", "Altruist Cult Mid-Age Male", 2 },
	{ "a_m_o_acult_01", "Altruist Cult Old Male", 2 },
	{ "a_m_o_acult_02", "Altruist Cult Old Male 2", 2 },
	{ "a_m_y_acult_01", "Altruist Cult Young Male", 2 },
	{ "a_m_y_acult_02", "Altruist Cult Young Male 2", 2 },
	{ "a_m_m_beach_01", "Beach Male", 2 },
	{ "a_m_m_beach_02", "Beach Male 2", 2 },
	{ "a_m_y_musclbeac_01", "Beach Muscle Male", 2 },
	{ "a_m_y_musclbeac_02", "Beach Muscle Male 2", 2 },
	{ "a_m_m_mlcrisis_01", "Midlife Crisis Casino Bikers", 2 },
	{ "a_m_y_gencaspat_01", "Casual Casino Guests", 2 },
	{ "a_m_y_smartcaspat_01", "Formel Casino Guests", 2 },
	{ "a_m_o_beach_01", "Beach Old Male", 2 },
	{ "a_m_m_trampbeac_01", "Beach Tramp Male", 2 },
	{ "a_m_y_beach_01", "Beach Young Male", 2 },
	{ "a_m_y_beach_02", "Beach Young Male 2", 2 },
	{ "a_m_y_beach_03", "Beach Young Male 3", 2 },
	{ "a_m_m_bevhills_01", "Beverly Hills Male", 2 },
	{ "a_m_m_bevhills_02", "Beverly Hills Male 2", 2 },
	{ "a_m_y_bevhills_01", "Beverly Hills Young Male", 2 },
	{ "a_m_y_bevhills_02", "Beverly Hills Young Male 2", 2 },
	{ "a_m_y_stbla_01", "Black Street Male", 2 },
	{ "a_m_y_stbla_02", "Black Street Male 2", 2 },
	{ "a_m_y_breakdance_01", "Breakdancer Male", 2 },
	{ "a_m_y_busicas_01", "Business Casual", 2 },
	{ "a_m_m_business_01", "Business Male", 2 },
	{ "a_m_y_business_01", "Business Young Male", 2 },
	{ "a_m_y_business_02", "Business Young Male 2", 2 },
	{ "a_m_y_business_03", "Business Young Male 3", 2 },
	{ "a_m_y_cyclist_01", "Cyclist Male", 2 },
	{ "a_m_y_dhill_01", "Downhill Cyclist", 2 },
	{ "a_m_y_downtown_01", "Downtown Male", 2 },
	{ "a_m_m_eastsa_01", "East SA Male", 2 },
	{ "a_m_m_eastsa_02", "East SA Male 2", 2 },
	{ "a_m_y_eastsa_01", "East SA Young Male", 2 },
	{ "a_m_y_eastsa_02", "East SA Young Male 2", 2 },
	{ "a_m_y_epsilon_01", "Epsilon Male", 2 },
	{ "a_m_y_epsilon_02", "Epsilon Male 2", 2 },
	{ "a_m_m_farmer_01", "Farmer", 2 },
	{ "a_m_m_fatlatin_01", "Fat Latino Male", 2 },
	{ "a_m_y_gay_01", "Gay Male", 2 },
	{ "a_m_y_gay_02", "Gay Male 2", 2 },
	{ "a_m_m_genfat_01", "General Fat Male", 2 },
	{ "a_m_m_genfat_02", "General Fat Male 2", 2 },
	{ "a_m_o_genstreet_01", "General Street Old Male", 2 },
	{ "a_m_y_genstreet_01", "General Street Young Male", 2 },
	{ "a_m_y_genstreet_02", "General Street Young Male 2", 2 },
	{ "a_m_m_golfer_01", "Golfer Male", 2 },
	{ "a_m_y_golfer_01", "Golfer Young Male", 2 },
	{ "a_m_m_hasjew_01", "Hasidic Jew Male", 2 },
	{ "a_m_y_hasjew_01", "Hasidic Jew Young Male", 2 },
	{ "a_m_y_hiker_01", "Hiker Male", 2 },
	{ "a_m_m_hillbilly_01", "Hillbilly Male", 2 },
	{ "a_m_m_hillbilly_02", "Hillbilly Male 2", 2 },
	{ "a_m_y_hippy_01", "Hippie Male", 2 },
	{ "a_m_y_hipster_01", "Hipster Male", 2 },
	{ "a_m_y_hipster_02", "Hipster Male 2", 2 },
	{ "a_m_y_hipster_03", "Hipster Male 3", 2 },
	{ "a_m_m_indian_01", "Indian Male", 2 },
	{ "a_m_y_indian_01", "Indian Young Male", 2 },
	{ "a_m_y_jetski_01", "Jetskier", 2 },
	{ "a_m_y_runner_01", "Jogger Male", 2 },
	{ "a_m_y_runner_02", "Jogger Male 2", 2 },
	{ "a_m_y_juggalo_01", "Juggalo Male", 2 },
	{ "a_m_m_ktown_01", "Korean Male", 2 },
	{ "a_m_o_ktown_01", "Korean Old Male", 2 },
	{ "a_m_y_ktown_01", "Korean Young Male", 2 },
	{ "a_m_y_ktown_02", "Korean Young Male 2", 2 },
	{ "a_m_m_stlat_02", "Latino Street Male 2", 2 },
	{ "a_m_y_stlat_01", "Latino Street Young Male", 2 },
	{ "a_m_y_latino_01", "Latino Young Male", 2 },
	{ "a_m_m_malibu_01", "Malibu Male", 2 },
	{ "a_m_y_methhead_01", "Meth Addict", 2 },
	{ "a_m_m_mexlabor_01", "Mexican Labourer", 2 },
	{ "a_m_m_mexcntry_01", "Mexican Rural", 2 },
	{ "a_m_y_mexthug_01", "Mexican Thug", 2 },
	{ "a_m_y_motox_01", "Motocross Biker", 2 },
	{ "a_m_y_motox_02", "Motocross Biker 2", 2 },
	{ "a_m_m_og_boss_01", "OG Boss", 2 },
	{ "a_m_m_paparazzi_01", "Paparazzi Male", 2 },
	{ "a_m_m_polynesian_01", "Polynesian", 2 },
	{ "a_m_y_polynesian_01", "Polynesian Young", 2 },
	{ "a_m_m_prolhost_01", "Prologue Host Male", 2 },
	{ "a_m_y_roadcyc_01", "Road Cyclist", 2 },
	{ "a_m_m_rurmeth_01", "Rural Meth Addict Male", 2 },
	{ "a_m_m_salton_01", "Salton Male", 2 },
	{ "a_m_m_salton_02", "Salton Male 2", 2 },
	{ "a_m_m_salton_03", "Salton Male 3", 2 },
	{ "a_m_m_salton_04", "Salton Male 4", 2 },
	{ "a_m_o_salton_01", "Salton Old Male", 2 },
	{ "a_m_y_salton_01", "Salton Young Male", 2 },
	{ "a_m_m_skater_01", "Skater Male", 2 },
	{ "a_m_y_skater_01", "Skater Young Male", 2 },
	{ "a_m_y_skater_02", "Skater Young Male 2", 2 },
	{ "a_m_m_skidrow_01", "Skid Row Male", 2 },
	{ "a_m_m_socenlat_01", "South Central Latino Male", 2 },
	{ "a_m_m_soucent_01", "South Central Male", 2 },
	{ "a_m_m_soucent_02", "South Central Male 2", 2 },
	{ "a_m_m_soucent_03", "South Central Male 3", 2 },
	{ "a_m_m_soucent_04", "South Central Male 4", 2 },
	{ "a_m_o_soucent_01", "South Central Old Male", 2 },
	{ "a_m_o_soucent_02", "South Central Old Male 2", 2 },
	{ "a_m_o_soucent_03", "South Central Old Male 3", 2 },
	{ "a_m_y_soucent_01", "South Central Young Male", 2 },
	{ "a_m_y_soucent_02", "South Central Young Male 2", 2 },
	{ "a_m_y_soucent_03", "South Central Young Male 3", 2 },
	{ "a_m_y_soucent_04", "South Central Young Male 4", 2 },
	{ "a_m_y_sunbathe_01", "Sunbather Male", 2 },
	{ "a_m_y_surfer_01", "Surfer", 2 },
	{ "a_m_m_tennis_01", "Tennis Player Male", 2 },
	{ "a_m_m_tourist_01", "Tourist Male", 2 },
	{ "a_m_m_tramp_01", "Tramp Male", 2 },
	{ "a_m_o_tramp_01", "Tramp Old Male", 2 },
	{ "a_m_m_tranvest_01", "Transvestite Male", 2 },
	{ "a_m_m_tranvest_02", "Transvestite Male 2", 2 },
	{ "a_m_y_beachvesp_01", "Vespucci Beach Male", 2 },
	{ "a_m_y_beachvesp_02", "Vespucci Beach Male 2", 2 },
	{ "a_m_y_vindouche_01", "Vinewood Douche", 2 },
	{ "a_m_y_vinewood_01", "Vinewood Male", 2 },
	{ "a_m_y_vinewood_02", "Vinewood Male 2", 2 },
	{ "a_m_y_vinewood_03", "Vinewood Male 3", 2 },
	{ "a_m_y_vinewood_04", "Vinewood Male 4", 2 },
	{ "a_m_y_stwhi_01", "White Street Male", 2 },
	{ "a_m_y_stwhi_02", "White Street Male 2", 2 },
	{ "a_m_y_yoga_01", "Yoga Male", 2 },
	{ "a_m_y_clubcust_01", "Club Customer Male 1", 2 },
	{ "a_m_y_clubcust_02", "Club Customer Male 2", 2 },
	{ "a_m_y_clubcust_03", "Club Customer Male 3", 2 },
	{ "csb_abigail", "Abigail Mathers", 3 },
	{ "csb_agent", "Agent", 3 },
	{ "csb_agatha", "Agatha Baker", 3 },
	{ "csb_avery", "Avery Duggan", 3 },
	{ "csb_mp_agent14", "Agent 14", 3 },
	{ "cs_amandatownley", "Amanda De Santa", 3 },
	{ "cs_andreas", "Andreas Sanchez", 3 },
	{ "csb_anita", "Anita Mendoza", 3 },
	{ "csb_anton", "Anton Beaudelaire", 3 },
	{ "cs_ashley", "Ashley Butler", 3 },
	{ "csb_avon", "Avon Hertz", 3 },
	{ "csb_ballasog", "Ballas OG", 3 },
	{ "cs_bankman", "Bank Manager", 3 },
	{ "cs_barry", "Barry", 3 },
	{ "cs_beverly", "Beverly Felton", 3 },
	{ "csb_brucie2", "Brucie Kibbutz", 3 },
	{ "cs_orleans", "Bigfoot", 3 },
	{ "csb_bogdan", "Bogdan", 3 },
	{ "cs_brad", "Brad", 3 },
	{ "cs_bradcadaver", "Brad's Cadaver", 3 },
	{ "csb_bride", "Bride", 3 },
	{ "csb_burgerdrug", "Burger Drug Worker", 3 },
	{ "csb_car3guy1", "Car 3 Guy 1", 3 },
	{ "csb_car3guy2", "Car 3 Guy 2", 3 },
	{ "cs_carbuyer", "Car Buyer", 3 },
	{ "cs_casey", "Casey", 3 },
	{ "csb_chef", "Chef", 3 },
	{ "csb_chef2", "Chef", 3 },
	{ "csb_chin_goon", "Chinese Goon", 3 },
	{ "cs_clay", "Clay Simons (The Lost)", 3 },
	{ "csb_cletus", "Cletus", 3 },
	{ "csb_cop", "Cop", 3 },
	{ "cs_chrisformage", "Cris Formage", 3 },
	{ "csb_customer", "Customer", 3 },
	{ "cs_dale", "Dale", 3 },
	{ "cs_davenorton", "Dave Norton", 3 },
	{ "cs_debra", "Debra", 3 },
	{ "cs_denise", "Denise", 3 },
	{ "csb_denise_friend", "Denise's Friend", 3 },
	{ "cs_devin", "Devin", 3 },
	{ "csb_popov", "Dima Popov", 3 },
	{ "cs_dom", "Dom Beasley", 3 },
	{ "cs_drfriedlander", "Dr. Friedlander", 3 },
	{ "cs_tomepsilon", "Epsilon Tom", 3 },
	{ "cs_fabien", "Fabien", 3 },
	{ "csb_ramp_gang", "Families Gang Member?", 3 },
	{ "cs_mrk", "Ferdinand Kerimov (Mr. K)", 3 },
	{ "cs_fbisuit_01", "FIB Suit", 3 },
	{ "cs_floyd", "Floyd Hebert", 3 },
	{ "csb_fos_rep", "FOS Rep?", 3 },
	{ "csb_g", "Gerald", 3 },
	{ "csb_groom", "Groom", 3 },
	{ "csb_grove_str_dlr", "Grove Street Dealer", 3 },
	{ "cs_guadalope", "Guadalope", 3 },
	{ "cs_gurk", "GURK?", 3 },
	{ "csb_hao", "Hao", 3 },
	{ "csb_ramp_hic", "Hick", 3 },
	{ "csb_ramp_hipster", "Hipster", 3 },
	{ "csb_hugh", "Hugh Welsh", 3 },
	{ "cs_hunter", "Hunter", 3 },
	{ "csb_imran", "Imran Shinowa", 3 },
	{ "csb_jackhowitzer", "Jack Howitzer", 3 },
	{ "cs_janet", "Janet", 3 },
	{ "csb_janitor", "Janitor", 3 },
	{ "cs_jewelass", "Jeweller Assistant", 3 },
	{ "cs_jimmyboston", "Jimmy Boston", 3 },
	{ "cs_jimmydisanto", "Jimmy De Santa", 3 },
	{ "cs_johnnyklebitz", "Johnny Klebitz", 3 },
	{ "cs_josef", "Josef", 3 },
	{ "cs_josh", "Josh", 3 },
	{ "cs_karen_daniels", "Karen Daniels", 3 },
	{ "cs_lamardavis", "Lamar Davis", 3 },
	{ "cs_lazlow", "Lazlow", 3 },
	{ "cs_lestercrest", "Lester Crest", 3 },
	{ "cs_lifeinvad_01", "Life Invader", 3 },
	{ "cs_magenta", "Magenta", 3 },
	{ "cs_manuel", "Manuel", 3 },
	{ "csb_ramp_marine", "Marine", 3 },
	{ "cs_marnie", "Marnie Allen", 3 },
	{ "cs_martinmadrazo", "Martin Madrazo", 3 },
	{ "cs_maryann", "Mary-Ann Quinn", 3 },
	{ "csb_maude", "Maude", 3 },
	{ "csb_rashcosvki", "Maxim Rashkovsky", 3 },
	{ "csb_mweather", "Merryweather Merc", 3 },
	{ "csb_ramp_mex", "Mexican", 3 },
	{ "cs_michelle", "Michelle", 3 },
	{ "cs_milton", "Milton McIlroy", 3 },
	{ "cs_joeminuteman", "Minuteman Joe", 3 },
	{ "cs_molly", "Molly", 3 },
	{ "csb_money", "Money Man", 3 },
	{ "cs_movpremf_01", "Movie Premiere Female", 3 },
	{ "cs_movpremmale", "Movie Premiere Male", 3 },
	{ "cs_mrsphillips", "Mrs. Phillips", 3 },
	{ "csb_mrs_r", "Mrs. Rackman", 3 },
	{ "cs_mrs_thornhill", "Mrs. Thornhill", 3 },
	{ "cs_natalia", "Natalia", 3 },
	{ "cs_nervousron", "Nervous Ron", 3 },
	{ "cs_nigel", "Nigel", 3 },
	{ "cs_old_man1a", "Old Man 1", 3 },
	{ "cs_old_man2", "Old Man 2", 3 },
	{ "cs_omega", "Omega", 3 },
	{ "csb_ortega", "Ortega", 3 },
	{ "csb_oscar", "Oscar", 3 },
	{ "csb_paige", "Paige Harris", 3 },
	{ "cs_patricia", "Patricia", 3 },
	{ "cs_dreyfuss", "Peter Dreyfuss", 3 },
	{ "csb_porndudes", "Porn Dude", 3 },
	{ "cs_priest", "Priest", 3 },
	{ "csb_prologuedriver", "Prologue Driver", 3 },
	{ "csb_prolsec", "Prologue Security", 3 },
	{ "cs_prolsec_02", "Prologue Security 2", 3 },
	{ "csb_reporter", "Reporter", 3 },
	{ "csb_roccopelosi", "Rocco Pelosi", 3 },
	{ "cs_russiandrunk", "Russian Drunk", 3 },
	{ "csb_screen_writer", "Screenwriter", 3 },
	{ "cs_siemonyetarian", "Simeon Yetarian", 3 },
	{ "cs_solomon", "Solomon Richards", 3 },
	{ "cs_stevehains", "Steve Haines", 3 },
	{ "cs_stretch", "Stretch", 3 },
	{ "csb_stripper_01", "Stripper", 3 },
	{ "csb_stripper_02", "Stripper 2", 3 },
	{ "cs_tanisha", "Tanisha", 3 },
	{ "cs_taocheng", "Tao Cheng", 3 },
	{ "cs_taocheng2", "Tao Cheng (Casino)", 3 },
	{ "cs_taostranslator", "Tao's Translator", 3 },
	{ "cs_taostranslator2", "Tao's Translator (Casino)", 3 },
	{ "cs_tenniscoach", "Tennis Coach", 3 },
	{ "cs_terry", "Terry", 3 },
	{ "cs_tom", "Tom", 3 },
	{ "csb_tomcasino", "Tom Connors", 3 },
	{ "csb_tonya", "Tonya", 3 },
	{ "csb_thornton", "Thornton Duggan", 3 },
	{ "cs_tracydisanto", "Tracey De Santa", 3 },
	{ "csb_trafficwarden", "Traffic Warden", 3 },
	{ "csb_undercover", "Undercover Cop", 3 },
	{ "cs_paper", "United Paper Man", 3 },
	{ "csb_vagspeak", "Vagos Speak", 3 },
	{ "csb_vincent", "Vincent (Casino)", 3 },
	{ "cs_wade", "Wade", 3 },
	{ "cs_chengsr", "Wei Cheng", 3 },
	{ "cs_zimbor", "Zimbor", 3 },
	{ "csb_djblamadon", "DJ Black Madonna", 3 },
	{ "csb_dix", "Dixon", 3 },
	{ "csb_englishdave", "English Dave", 3 },
	{ "cs_lazlow_2", "Lazlow 2", 3 },
	{ "csb_sol", "Soloman", 3 },
	{ "csb_talcc", "Tale of Us 1", 3 },
	{ "csb_talmm", "Tale of Us 2", 3 },
	{ "csb_tonyprince", "Tony Prince", 3 },
	{ "csb_alan", "Alan Jerome", 3 },
	{ "csb_bryony", "Bryony", 3 },
	{ "g_f_y_ballas_01", "Ballas Female", 4 },
	{ "g_f_y_families_01", "Families Female", 4 },
	{ "g_f_importexport_01", "Import Export Female", 4 },
	{ "g_f_y_lost_01", "The Lost MC Female", 4 },
	{ "g_f_y_vagos_01", "Vagos Female", 4 },
	{ "g_f_importexport_01", "Gang Female (Import-Export)", 5 },
	{ "g_m_importexport_01", "Gang Male (Import-Export)", 5 },
	{ "g_m_m_armboss_01", "Armenian Boss", 5 },
	{ "g_m_m_armgoon_01", "Armenian Goon", 5 },
	{ "g_m_y_armgoon_02", "Armenian Goon 2", 5 },
	{ "g_m_m_armlieut_01", "Armenian Lieutenant", 5 },
	{ "g_m_y_azteca_01", "Azteca", 5 },
	{ "g_m_y_ballaeast_01", "Ballas East Male", 5 },
	{ "g_m_y_ballaorig_01", "Ballas Original Male", 5 },
	{ "g_m_y_ballasout_01", "Ballas South Male", 5 },
	{ "g_m_m_casrn_01", "Casino Guests?", 5 },
	{ "g_m_m_chemwork_01", "Chemical Plant Worker", 5 },
	{ "g_m_m_chiboss_01", "Chinese Boss", 5 },
	{ "g_m_m_chigoon_01", "Chinese Goon", 5 },
	{ "g_m_m_chigoon_02", "Chinese Goon 2", 5 },
	{ "g_m_m_chicold_01", "Chinese Goon Older", 5 },
	{ "g_m_y_famca_01", "Families CA Male", 5 },
	{ "g_m_y_famdnf_01", "Families DNF Male", 5 },
	{ "g_m_y_famfor_01", "Families FOR Male", 5 },
	{ "g_m_m_korboss_01", "Korean Boss", 5 },
	{ "g_m_y_korlieut_01", "Korean Lieutenant", 5 },
	{ "g_m_y_korean_01", "Korean Young Male", 5 },
	{ "g_m_y_korean_02", "Korean Young Male 2", 5 },
	{ "g_m_m_mexboss_01", "Mexican Boss", 5 },
	{ "g_m_m_mexboss_02", "Mexican Boss 2", 5 },
	{ "g_m_y_mexgang_01", "Mexican Gang Member", 5 },
	{ "g_m_y_mexgoon_01", "Mexican Goon", 5 },
	{ "g_m_y_mexgoon_02", "Mexican Goon 2", 5 },
	{ "g_m_y_mexgoon_03", "Mexican Goon 3", 5 },
	{ "g_m_y_pologoon_01", "Polynesian Goon", 5 },
	{ "g_m_y_pologoon_02", "Polynesian Goon 2", 5 },
	{ "g_m_y_salvaboss_01", "Salvadoran Boss", 5 },
	{ "g_m_y_salvagoon_01", "Salvadoran Goon", 5 },
	{ "g_m_y_salvagoon_02", "Salvadoran Goon 2", 5 },
	{ "g_m_y_salvagoon_03", "Salvadoran Goon 3", 5 },
	{ "g_m_y_strpunk_01", "Street Punk", 5 },
	{ "g_m_y_strpunk_02", "Street Punk 2", 5 },
	{ "g_m_y_lost_01", "The Lost MC Male", 5 },
	{ "g_m_y_lost_02", "The Lost MC Male 2", 5 },
	{ "g_m_y_lost_03", "The Lost MC Male 3", 5 },
	{ "player_zero", "Michael", 6 },
	{ "player_one", "Franklin", 6 },
	{ "player_two", "Trevor", 6 },
	{ "ig_abigail", "Abigail Mathers", 6 },
	{ "ig_agent", "Agent", 6 },
	{ "ig_agatha", "Agatha Baker", 6 },
	{ "ig_avery", "Avery Duggan", 6 },
	{ "ig_mp_agent14", "Agent 14", 6 },
	{ "ig_amandatownley", "Amanda De Santa", 6 },
	{ "ig_andreas", "Andreas Sanchez", 6 },
	{ "ig_ashley", "Ashley Butler", 6 },
	{ "ig_avon", "Avon Hertz", 6 },
	{ "ig_ballasog", "Ballas OG", 6 },
	{ "ig_benny", "Benny", 6 },
	{ "ig_bankman", "Bank Manager", 6 },
	{ "ig_barry", "Barry", 6 },
	{ "ig_bestmen", "Best Man", 6 },
	{ "ig_beverly", "Beverly Felton", 6 },
	{ "ig_brucie2", "Brucie Kibbutz", 6 },
	{ "ig_orleans", "Bigfoot", 6 },
	{ "ig_brad", "Brad", 6 },
	{ "ig_bride", "Bride", 6 },
	{ "ig_car3guy1", "Car 3 Guy 1", 6 },
	{ "ig_car3guy2", "Car 3 Guy 2", 6 },
	{ "ig_casey", "Casey", 6 },
	{ "ig_chef", "Chef", 6 },
	{ "ig_chef2", "Chef", 6 },
	{ "ig_claypain", "Clay Jackson (The Pain Giver)", 6 },
	{ "ig_clay", "Clay Simons (The Lost)", 6 },
	{ "ig_cletus", "Cletus", 6 },
	{ "ig_chrisformage", "Cris Formage", 6 },
	{ "ig_dale", "Dale", 6 },
	{ "ig_davenorton", "Dave Norton", 6 },
	{ "ig_denise", "Denise", 6 },
	{ "ig_devin", "Devin", 6 },
	{ "ig_popov", "Dima Popov", 6 },
	{ "ig_dom", "Dom Beasley", 6 },
	{ "ig_drfriedlander", "Dr. Friedlander", 6 },
	{ "ig_tomepsilon", "Epsilon Tom", 6 },
	{ "ig_fabien", "Fabien", 6 },
	{ "ig_ramp_gang", "Families Gang Member?", 6 },
	{ "ig_mrk", "Ferdinand Kerimov (Mr. K)", 6 },
	{ "ig_fbisuit_01", "FIB Suit", 6 },
	{ "ig_floyd", "Floyd Hebert", 6 },
	{ "ig_g", "Gerald", 6 },
	{ "ig_groom", "Groom", 6 },
	{ "ig_hao", "Hao", 6 },
	{ "ig_ramp_hic", "Hick", 6 },
	{ "ig_ramp_hipster", "Hipster", 6 },
	{ "ig_hunter", "Hunter", 6 },
	{ "ig_janet", "Janet", 6 },
	{ "ig_jay_norris", "Jay Norris", 6 },
	{ "ig_jewelass", "Jeweller Assistant", 6 },
	{ "ig_jimmyboston", "Jimmy Boston", 6 },
	{ "ig_jimmydisanto", "Jimmy De Santa", 6 },
	{ "ig_johnnyklebitz", "Johnny Klebitz", 6 },
	{ "ig_josef", "Josef", 6 },
	{ "ig_josh", "Josh", 6 },
	{ "ig_karen_daniels", "Karen Daniels", 6 },
	{ "ig_kerrymcintosh", "Kerry McIntosh", 6 },
	{ "ig_lamardavis", "Lamar Davis", 6 },
	{ "ig_lazlow", "Lazlow", 6 },
	{ "ig_lestercrest", "Lester Crest", 6 },
	{ "ig_lestercrest_2", "Lester Crest (Doomsday Heist)", 6 },
	{ "ig_lifeinvad_01", "Life Invader", 6 },
	{ "ig_lifeinvad_02", "Life Invader 2", 6 },
	{ "ig_magenta", "Magenta", 6 },
	{ "ig_manuel", "Manuel", 6 },
	{ "ig_marnie", "Marnie Allen", 6 },
	{ "ig_maryann", "Mary-Ann Quinn", 6 },
	{ "ig_maude", "Maude", 6 },
	{ "ig_rashcosvki", "Maxim Rashkovsky", 6 },
	{ "ig_ramp_mex", "Mexican", 6 },
	{ "ig_michelle", "Michelle", 6 },
	{ "ig_milton", "Milton McIlroy", 6 },
	{ "ig_joeminuteman", "Minuteman Joe", 6 },
	{ "ig_malc", "Malc", 6 },
	{ "ig_molly", "Molly", 6 },
	{ "ig_money", "Money Man", 6 },
	{ "ig_mrsphillips", "Mrs. Phillips", 6 },
	{ "ig_mrs_thornhill", "Mrs. Thornhill", 6 },
	{ "ig_natalia", "Natalia", 6 },
	{ "ig_nervousron", "Nervous Ron", 6 },
	{ "ig_nigel", "Nigel", 6 },
	{ "ig_old_man1a", "Old Man 1", 6 },
	{ "ig_old_man2", "Old Man 2", 6 },
	{ "ig_omega", "Omega", 6 },
	{ "ig_oneil", "O'Neil Brothers", 6 },
	{ "ig_ortega", "Ortega", 6 },
	{ "ig_paige", "Paige Harris", 6 },
	{ "ig_patricia", "Patricia", 6 },
	{ "ig_dreyfuss", "Peter Dreyfuss", 6 },
	{ "ig_priest", "Priest", 6 },
	{ "ig_prolsec_02", "Prologue Security 2", 6 },
	{ "ig_roccopelosi", "Rocco Pelosi", 6 },
	{ "ig_russiandrunk", "Russian Drunk", 6 },
	{ "ig_screen_writer", "Screenwriter", 6 },
	{ "ig_siemonyetarian", "Simeon Yetarian", 6 },
	{ "ig_solomon", "Solomon Richards", 6 },
	{ "ig_stevehains", "Steve Haines", 6 },
	{ "ig_stretch", "Stretch", 6 },
	{ "ig_talina", "Talina", 6 },
	{ "ig_tanisha", "Tanisha", 6 },
	{ "ig_taocheng", "Tao Cheng", 6 },
	{ "ig_taocheng2", "Tao Cheng (Casino)", 6 },
	{ "ig_taostranslator", "Tao's Translator", 6 },
	{ "ig_taostranslator2", "Tao's Translator (Casino)", 6 },
	{ "ig_tenniscoach", "Tennis Coach", 6 },
	{ "ig_terry", "Terry", 6 },
	{ "ig_tonya", "Tonya", 6 },
	{ "ig_tracydisanto", "Tracey De Santa", 6 },
	{ "ig_trafficwarden", "Traffic Warden", 6 },
	{ "ig_tylerdix", "Tyler Dixon", 6 },
	{ "ig_paper", "United Paper Man", 6 },
	{ "ig_vagspeak", "Vagos Funeral Speaker", 6 },
	{ "ig_wade", "Wade", 6 },
	{ "ig_chengsr", "Wei Cheng", 6 },
	{ "ig_zimbor", "Zimbor", 6 },
	{ "ig_djblamadon", "DJ Black Madonna", 6 },
	{ "ig_djblamryans", "DJ Ryan S", 6 },
	{ "ig_djblamrupert", "DJ Rupert", 6 },
	{ "ig_djdixmanager", "DJ Dixon Manager", 6 },
	{ "ig_djsolfotios", "DJ Fotios", 6 },
	{ "ig_djsoljakob", "DJ Jakob", 6 },
	{ "ig_djsolmike", "DJ Mike T", 6 },
	{ "ig_djsolrobt", "DJ Rob T", 6 },
	{ "ig_djtalaurelia", " DJ Aurelia", 6 },
	{ "ig_djtalignazio", "DJ Ignazio", 6 },
	{ "ig_dix", "Dixon", 6 },
	{ "ig_englishdave", "English Dave", 6 },
	{ "ig_djgeneric_01", "Generic DJ", 6 },
	{ "ig_jimmyboston_02", "Jimmy Boston 2", 6 },
	{ "ig_kerrymcintosh_02", "Kerry McIntosh 2", 6 },
	{ "ig_lacey_jones_02", "Lacy Jones 2", 6 },
	{ "ig_lazlow_2", "Lazlow 2", 6 },
	{ "ig_sol", "Soloman", 6 },
	{ "ig_djsolmanager", "Soloman Manager", 6 },
	{ "ig_talcc", "Tale of Us 1", 6 },
	{ "ig_talmm", "Tale of Us 2", 6 },
	{ "ig_tylerdix_02", "Tyler Dixon 2", 6 },
	{ "ig_tonyprince", "Tony Prince", 6 },
	{ "ig_sacha", "Sacha Yetarian", 6 },
	{ "ig_thornton", "Thornton Duggan", 6 },
	{ "ig_tomcasino", "Tom Connors", 6 },
	{ "ig_vincent", "Vincent (Casino)", 6 },
	{ "mp_s_m_armoured_01", "Armoured Van Security Male", 7 },
	{ "mp_m_avongoon", "Avon Goon", 7 },
	{ "mp_f_cocaine_01", "Biker Cocaine Female", 7 },
	{ "mp_m_cocaine_01", "Biker Cocaine Male", 7 },
	{ "mp_f_counterfeit_01", "Biker Counterfeit Female", 7 },
	{ "mp_m_counterfeit_01", "Biker Counterfeit Male", 7 },
	{ "mp_f_forgery_01", "Biker Forgery Female", 7 },
	{ "mp_m_forgery_01", "Biker Forgery Male", 7 },
	{ "mp_f_meth_01", "Biker Meth Female", 7 },
	{ "mp_m_meth_01", "Biker Meth Male", 7 },
	{ "mp_f_weed_01", "Biker Weed Female", 7 },
	{ "mp_m_weed_01", "Biker Weed Male", 7 },
	{ "mp_f_boatstaff_01", "Boat-Staff Female", 7 },
	{ "mp_m_boatstaff_01", "Boat-Staff Male", 7 },
	{ "mp_m_bogdangoon", "Bogdan Goon", 7 },
	{ "mp_f_chbar_01", "Clubhouse Bar Female", 7 },
	{ "mp_m_claude_01", "Claude Speed", 7 },
	{ "mp_f_deadhooker", "Dead Hooker", 7 },
	{ "mp_m_exarmy_01", "Ex-Army Male", 7 },
	{ "mp_f_execpa_01", "Executive PA Female", 7 },
	{ "mp_f_execpa_02", "Executive PA Female 2", 7 },
	{ "mp_m_execpa_01", "Executive PA Male", 7 },
	{ "mp_m_famdd_01", "Families DD Male", 7 },
	{ "mp_m_fibsec_01", "FIB Security", 7 },
	{ "mp_f_freemode_01", "Freemode Female", 7 },
	{ "mp_m_freemode_01", "Freemode Male", 7 },
	{ "mp_f_helistaff_01", "Heli-Staff Female", 7 },
	{ "mp_m_marston_01", "John Marston", 7 },
	{ "mp_f_misty_01", "Misty", 7 },
	{ "mp_m_niko_01", "Niko Bellic", 7 },
	{ "mp_f_cardesign_01", "Office Garage Mechanic (Female)", 7 },
	{ "mp_g_m_pros_01", "Pros", 7 },
	{ "mp_m_securoguard_01", "Securoserve Guard (Male)", 7 },
	{ "mp_m_shopkeep_01", "Shopkeeper (Male)", 7 },
	{ "mp_f_stripperlite", "Stripper Lite (Female)", 7 },
	{ "mp_m_g_vagfun_01", "Vagos Funeral", 7 },
	{ "mp_m_waremech_01", "Warehouse Mechanic (Male)", 7 },
	{ "mp_m_weapexp_01", "Weapon Exp (Male)", 7 },
	{ "mp_m_weapwork_01", "Weapon Work (Male)", 7 },
	{ "mp_f_bennymech_01", "Benny Mechanic (Female)", 7 },
	{ "s_f_y_airhostess_01", "Air Hostess", 8 },
	{ "s_f_m_fembarber", "Barber Female", 8 },
	{ "s_f_y_bartender_01", "Bartender", 8 },
	{ "s_f_y_baywatch_01", "Baywatch Female", 8 },
	{ "s_f_y_casino_01", "Casino Staff", 8 },
	{ "s_f_y_cop_01", "Cop Female", 8 },
	{ "s_f_y_factory_01", "Factory Worker Female", 8 },
	{ "s_f_y_hooker_01", "Hooker", 8 },
	{ "s_f_y_hooker_02", "Hooker 2", 8 },
	{ "s_f_y_hooker_03", "Hooker 3", 8 },
	{ "s_f_y_scrubs_01", "Hospital Scrubs Female", 8 },
	{ "s_f_m_maid_01", "Maid", 8 },
	{ "s_f_y_migrant_01", "Migrant Female", 8 },
	{ "s_f_y_movprem_01", "Movie Premiere Female", 8 },
	{ "s_f_y_ranger_01", "Ranger Female", 8 },
	{ "s_f_m_shop_high", "Sales Assistant (High-End)", 8 },
	{ "s_f_y_shop_low", "Sales Assistant (Low-End)", 8 },
	{ "s_f_y_shop_mid", "Sales Assistant (Mid-Price)", 8 },
	{ "s_f_y_sheriff_01", "Sheriff Female", 8 },
	{ "s_f_y_stripper_01", "Stripper", 8 },
	{ "s_f_y_stripper_02", "Stripper 2", 8 },
	{ "s_f_y_stripperlite", "Stripper Lite", 8 },
	{ "s_f_m_sweatshop_01", "Sweatshop Worker", 8 },
	{ "s_f_y_sweatshop_01", "Sweatshop Worker Young", 8 },
	{ "s_f_y_clubbar_01", "Club Bartender Female", 8 },
	{ "s_m_y_airworker", "Air Worker Male", 9 },
	{ "s_m_m_movalien_01", "Alien", 9 },
	{ "s_m_y_ammucity_01", "Ammu-Nation City Clerk", 9 },
	{ "s_m_m_ammucountry", "Ammu-Nation Rural Clerk", 9 },
	{ "s_m_m_armoured_01", "Armoured Van Security", 9 },
	{ "s_m_m_armoured_02", "Armoured Van Security 2", 9 },
	{ "s_m_y_armymech_01", "Army Mechanic", 9 },
	{ "s_m_y_autopsy_01", "Autopsy Tech", 9 },
	{ "s_m_m_autoshop_01", "Autoshop Worker", 9 },
	{ "s_m_m_autoshop_02", "Autoshop Worker 2", 9 },
	{ "s_m_y_barman_01", "Barman", 9 },
	{ "s_m_m_cntrybar_01", "Bartender (Rural)", 9 },
	{ "s_m_y_baywatch_01", "Baywatch Male", 9 },
	{ "s_m_y_blackops_01", "Black Ops Soldier", 9 },
	{ "s_m_y_blackops_02", "Black Ops Soldier 2", 9 },
	{ "s_m_y_blackops_03", "Black Ops Soldier 3", 9 },
	{ "s_m_m_bouncer_01", "Bouncer", 9 },
	{ "s_m_y_busboy_01", "Busboy", 9 },
	{ "s_m_o_busker_01", "Busker", 9 },
	{ "s_m_y_casino_01", "Casino Staff", 9 },
	{ "s_m_y_chef_01", "Chef", 9 },
	{ "s_m_m_chemsec_01", "Chemical Plant Security", 9 },
	{ "s_m_y_clown_01", "Clown", 9 },
	{ "s_m_y_construct_01", "construction Worker", 9 },
	{ "s_m_y_construct_02", "construction Worker 2", 9 },
	{ "s_m_y_cop_01", "Cop Male", 9 },
	{ "s_m_m_ccrew_01", "Crew Member", 9 },
	{ "s_m_y_dealer_01", "Dealer", 9 },
	{ "s_m_y_devinsec_01", "Devin's Security", 9 },
	{ "s_m_m_dockwork_01", "Dock Worker", 9 },
	{ "s_m_y_dockwork_01", "Dock Worker", 9 },
	{ "s_m_m_doctor_01", "Doctor", 9 },
	{ "s_m_y_doorman_01", "Doorman", 9 },
	{ "s_m_y_dwservice_01", "DW Airport Worker", 9 },
	{ "s_m_y_dwservice_02", "DW Airport Worker 2", 9 },
	{ "s_m_y_factory_01", "Factory Worker Male", 9 },
	{ "s_m_m_fiboffice_01", "FIB Office Worker", 9 },
	{ "s_m_m_fiboffice_02", "FIB Office Worker 2", 9 },
	{ "s_m_m_fibsec_01", "FIB Security", 9 },
	{ "s_m_y_fireman_01", "Fireman Male", 9 },
	{ "s_m_m_gaffer_01", "Gaffer", 9 },
	{ "s_m_y_garbage", "Garbage Worker", 9 },
	{ "s_m_m_gardener_01", "Gardener", 9 },
	{ "s_m_y_grip_01", "Grip", 9 },
	{ "s_m_m_hairdress_01", "Hairdresser Male", 9 },
	{ "s_m_m_highsec_01", "High Security", 9 },
	{ "s_m_m_highsec_02", "High Security 2", 9 },
	{ "s_m_y_hwaycop_01", "Highway Cop", 9 },
	{ "s_m_m_ciasec_01", "IAA Security", 9 },
	{ "s_m_m_janitor", "Janitor", 9 },
	{ "s_m_m_lathandy_01", "Latino Handyman Male", 9 },
	{ "s_m_m_lifeinvad_01", "Life Invader Male", 9 },
	{ "s_m_m_linecook", "Line Cook", 9 },
	{ "s_m_m_lsmetro_01", "LS Metro Worker Male", 9 },
	{ "s_m_m_mariachi_01", "Mariachi", 9 },
	{ "s_m_m_marine_01", "Marine", 9 },
	{ "s_m_m_marine_02", "Marine 2", 9 },
	{ "s_m_y_marine_01", "Marine Young", 9 },
	{ "s_m_y_marine_02", "Marine Young 2", 9 },
	{ "s_m_y_marine_03", "Marine Young 3", 9 },
	{ "s_m_y_xmech_01", "Mechanic", 9 },
	{ "s_m_y_xmech_02", "MC Clubhouse Mechanic", 9 },
	{ "s_m_m_migrant_01", "Migrant Male", 9 },
	{ "s_m_y_mime", "Mime Artist", 9 },
	{ "s_m_m_movspace_01", "Movie Astronaut", 9 },
	{ "s_m_m_movprem_01", "Movie Premiere Male", 9 },
	{ "s_m_m_paramedic_01", "Paramedic", 9 },
	{ "s_m_y_pestcont_01", "Pest Control", 9 },
	{ "s_m_m_pilot_01", "Pilot", 9 },
	{ "s_m_y_pilot_01", "Pilot", 9 },
	{ "s_m_m_pilot_02", "Pilot 2", 9 },
	{ "s_m_m_postal_01", "Postal Worker Male", 9 },
	{ "s_m_m_postal_02", "Postal Worker Male 2", 9 },
	{ "s_m_m_prisguard_01", "Prison Guard", 9 },
	{ "s_m_y_prisoner_01", "Prisoner", 9 },
	{ "s_m_y_prismuscl_01", "Prisoner (Muscular)", 9 },
	{ "s_m_y_ranger_01", "Ranger Male", 9 },
	{ "s_m_y_robber_01", "Robber", 9 },
	{ "s_m_y_shop_mask", "Mask Salesman", 9 },
	{ "s_m_m_scientist_01", "Scientist", 9 },
	{ "s_m_m_security_01", "Security Guard", 9 },
	{ "s_m_y_sheriff_01", "Sheriff Male", 9 },
	{ "s_m_m_snowcop_01", "Snow Cop Male", 9 },
	{ "s_m_m_strperf_01", "Street Performer", 9 },
	{ "s_m_m_strpreach_01", "Street Preacher", 9 },
	{ "s_m_m_strvend_01", "Street Vendor", 9 },
	{ "s_m_y_strvend_01", "Street Vendor Young", 9 },
	{ "s_m_y_swat_01", "SWAT", 9 },
	{ "s_m_m_gentransport", "Transport Worker Male", 9 },
	{ "s_m_m_trucker_01", "Trucker Male", 9 },
	{ "s_m_m_ups_01", "UPS Driver", 9 },
	{ "s_m_m_ups_02", "UPS Driver 2", 9 },
	{ "s_m_y_uscg_01", "US Coastguard", 9 },
	{ "s_m_y_valet_01", "Valet", 9 },
	{ "s_m_y_waiter_01", "Waiter", 9 },
	{ "s_m_y_westsec_01", "Duggan Secruity", 9 },
	{ "s_m_y_winclean_01", "Window Cleaner", 9 },
	{ "s_m_y_clubbar_01", "Club Bartender Male", 9 },
	{ "s_m_y_waretech_01", "Warehouse Technician", 9 },
	{ "u_f_y_bikerchic", "Biker Chic Female", 10 },
	{ "u_f_m_corpse_01", "Corpse Female", 10 },
	{ "u_f_m_casinocash_01", "Casino Cashier", 10 },
	{ "u_f_m_casinoshop_01", "Casino shop owner", 10 },
	{ "u_f_m_debbie_01", "Debbie (Agatha´s Secretary)", 10 },
	{ "u_f_o_carol", "Carol", 10 },
	{ "u_f_o_eileen", "Eileen", 10 },
	{ "u_f_y_beth", "Beth", 10 },
	{ "u_f_y_lauren", "Lauren", 10 },
	{ "u_f_y_taylor", "Taylor", 10 },
	{ "u_f_y_corpse_01", "Corpse Young Female", 10 },
	{ "u_f_y_corpse_02", "Corpse Young Female 2", 10 },
	{ "u_f_y_hotposh_01", "Hot Posh Female", 10 },
	{ "u_f_y_comjane", "Jane", 10 },
	{ "u_f_y_jewelass_01", "Jeweller Assistant", 10 },
	{ "u_f_m_miranda", "Miranda", 10 },
	{ "u_f_y_mistress", "Mistress", 10 },
	{ "u_f_o_moviestar", "Movie Star Female", 10 },
	{ "u_f_y_poppymich", "Poppy Mitchell", 10 },
	{ "u_f_y_princess", "Princess", 10 },
	{ "u_f_o_prolhost_01", "Prologue Host Old Female", 10 },
	{ "u_f_m_promourn_01", "Prologue Mourner Female", 10 },
	{ "u_f_y_spyactress", "Spy Actress", 10 },
	{ "u_f_m_miranda_02", "Miranda 2", 10 },
	{ "u_f_y_poppymich_02", "Poppy Mitchell 2", 10 },
	{ "u_f_y_danceburl_01", "Female Club Dancer (Burlesque)", 10 },
	{ "u_f_y_dancelthr_01", "Female Club Dancer (Leather)", 10 },
	{ "u_f_y_dancerave_01", "Female Club Dancer (Rave)", 10 },
	{ "u_m_y_abner", "Abner", 11 },
	{ "u_m_m_aldinapoli", "Al Di Napoli Male", 11 },
	{ "u_m_y_antonb", "Anton Beaudelaire", 11 },
	{ "u_m_y_juggernaut_01", "Avon Juggernaut", 11 },
	{ "u_m_y_babyd", "Baby D", 11 },
	{ "u_m_m_bankman", "Bank Manager Male", 11 },
	{ "u_m_m_bikehire_01", "Bike Hire Guy", 11 },
	{ "u_m_m_blane", "Blane", 11 },
	{ "u_m_m_curtis", "Curtis", 11 },
	{ "u_m_m_vince", "Vince", 11 },
	{ "u_m_o_dean", "Dean", 11 },
	{ "u_m_y_caleb", "Caleb", 11 },
	{ "u_m_y_croupthief_01", "Casino Thief", 11 },
	{ "u_m_y_gabriel", "Gabriel", 11 },
	{ "u_m_y_ushi", "Ushi", 11 },
	{ "u_m_y_burgerdrug_01", "Burger Drug Worker", 11 },
	{ "u_m_y_chip", "Chip", 11 },
	{ "u_m_y_cyclist_01", "Cyclist Male", 11 },
	{ "u_m_y_corpse_01", "Dead Courier", 11 },
	{ "u_m_m_doa_01", "DOA Man", 11 },
	{ "u_m_m_edtoh", "Ed Toh", 11 },
	{ "u_m_y_militarybum", "Ex-Mil Bum", 11 },
	{ "u_m_m_fibarchitect", "FIB Architect", 11 },
	{ "u_m_y_fibmugger_01", "FIB Mugger", 11 },
	{ "u_m_o_finguru_01", "Financial Guru", 11 },
	{ "u_m_m_glenstank_01", "Glen-Stank Male", 11 },
	{ "u_m_m_griff_01", "Griff", 11 },
	{ "u_m_y_guido_01", "Guido", 11 },
	{ "u_m_y_gunvend_01", "Gun Vendor", 11 },
	{ "u_m_y_smugmech_01", "Hangar Mechanic", 11 },
	{ "u_m_y_hippie_01", "Hippie Male", 11 },
	{ "u_m_m_streetart_01", "Street Art Male", 11 },
	{ "u_m_y_imporage", "Impotent Rage", 11 },
	{ "u_m_o_taphillbilly", "Jesco White (Tapdancing Hillbilly)", 11 },
	{ "u_m_m_jesus_01", "Jesus", 11 },
	{ "u_m_m_jewelthief", "Jewel Thief", 11 },
	{ "u_m_m_jewelsec_01", "Jeweller Security", 11 },
	{ "u_m_y_justin", "Justin", 11 },
	{ "u_m_y_baygor", "Kifflom Guy", 11 },
	{ "u_m_m_willyfist", "Love Fist Willy", 11 },
	{ "u_m_y_mani", "Mani", 11 },
	{ "u_m_m_markfost", "Mark Fostenburg", 11 },
	{ "u_m_m_filmdirector", "Movie Director", 11 },
	{ "u_m_o_filmnoir", "Movie Corpse (Suited)", 11 },
	{ "u_m_y_paparazzi", "Paparazzi Young Male", 11 },
	{ "u_m_m_partytarget", "Party Target", 11 },
	{ "u_m_y_party_01", "Partygoer", 11 },
	{ "u_m_y_pogo_01", "Pogo the Monkey", 11 },
	{ "u_m_y_prisoner_01", "Prisoner", 11 },
	{ "u_m_y_proldriver_01", "Prologue Driver", 11 },
	{ "u_m_m_promourn_01", "Prologue Mourner Male", 11 },
	{ "u_m_m_prolsec_01", "Prologue Security", 11 },
	{ "u_m_y_rsranger_01", "Republican Space Ranger", 11 },
	{ "u_m_m_rivalpap", "Rival Paparazzo", 11 },
	{ "u_m_y_sbike", "Sports Biker", 11 },
	{ "u_m_m_spyactor", "Spy Actor", 11 },
	{ "u_m_y_staggrm_01", "Stag Party Groom", 11 },
	{ "u_m_y_tattoo_01", "Tattoo Artist", 11 },
	{ "u_m_o_tramp_01", "Tramp Old Male", 11 },
	{ "u_m_y_zombie_01", "Zombie", 11 },
	{ "u_m_y_danceburl_01", "Male Club Dancer (Burlesque)", 11 },
	{ "u_m_y_dancelthr_01", "Male Club Dancer (Leather)", 11 },
	{ "u_m_y_dancerave_01", "Male Club Dancer (Rave)", 11 },
	{ "hc_driver", "Jewel Heist Driver",  12 },
	{ "hc_gunman", "Jewel Heist Gunman",  12 },
	{ "hc_hacker", "Jewel Heist Hacker",  12 },

};
static int l_CountForModels;
static int l_CountForModelsHash;
static int l_pickedModelSub = 1;
static int l_pickedModel = 1;
bool l_ModelLoaded;
const char* l_ModelNameArray[750];
const char* l_ModelHashArray[750];
inline char* StringToChar(std::string string) // Handy little thing
{
	return _strdup(string.c_str());
}
void horizonTick()
{
	const char* AimingModes[4] = { "Assisted Aim - Full", "Assisted Aim - Partial", "Free Aim - Assisted" , "Free Aim" };
	const char* ModelSubNames[13] = {
		"Animal Models", "Ambient Female Models", "Ambient Male Models", "Cutscene Models",
		"Gang Female Models", "Gang Male Models", "Story Models", "Multiplayer Models", "Scenario Female Models",
		"Scenario Male Models", "Story Scenario Female Models", "Story Scenario Male Models", "Other Models",
	};
	auto& style = ImGui::GetStyle();
	style.WindowPadding = { 10.f, 10.f };
	style.PopupRounding = 0.f;
	style.FramePadding = { 8.f, 4.f };
	style.ItemSpacing = { 10.f, 8.f };
	style.ItemInnerSpacing = { 6.f, 6.f };
	style.TouchExtraPadding = { 0.f, 0.f };
	style.IndentSpacing = 21.f;
	style.ScrollbarSize = 15.f;
	style.GrabMinSize = 8.f;
	style.WindowBorderSize = 1.f;
	style.ChildBorderSize = 0.f;
	style.PopupBorderSize = 1.f;
	style.FrameBorderSize = 0.f;
	style.TabBorderSize = 0.f;
	style.WindowRounding = 0.f;
	style.ChildRounding = 0.f;
	style.FrameRounding = 0.f;
	style.ScrollbarRounding = 0.f;
	style.GrabRounding = 0.f;
	style.TabRounding = 0.f;
	style.WindowTitleAlign = { 0.5f, 0.5f };
	style.ButtonTextAlign = { 0.5f, 0.5f };
	style.DisplaySafeAreaPadding = { 3.f, 3.f };

	auto& colors = style.Colors;
	colors[ImGuiCol_Text] = ImVec4(1.00f, 1.00f, 1.00f, 1.00f);
	colors[ImGuiCol_TextDisabled] = ImVec4(1.00f, 0.90f, 0.19f, 1.00f);
	colors[ImGuiCol_WindowBg] = ImVec4(0.06f, 0.06f, 0.06f, .80f);
	colors[ImGuiCol_ChildBg] = ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
	colors[ImGuiCol_PopupBg] = ImVec4(0.08f, 0.08f, 0.08f, 0.94f);
	colors[ImGuiCol_Border] = ImVec4(0.30f, 0.30f, 0.30f, 1.0f);
	colors[ImGuiCol_BorderShadow] = ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
	colors[ImGuiCol_FrameBg] = ImVec4(0.21f, 0.21f, 0.21f, 0.54f);
	colors[ImGuiCol_FrameBgHovered] = ImVec4(0.21f, 0.21f, 0.21f, 0.78f);
	colors[ImGuiCol_FrameBgActive] = ImVec4(0.28f, 0.27f, 0.27f, 0.54f);
	colors[ImGuiCol_TitleBg] = ImVec4(0.17f, 0.17f, 0.17f, 1.00f);
	colors[ImGuiCol_TitleBgActive] = ImVec4(0.19f, 0.19f, 0.19f, 1.00f);
	colors[ImGuiCol_TitleBgCollapsed] = ImVec4(0.00f, 0.00f, 0.00f, 0.51f);
	colors[ImGuiCol_MenuBarBg] = ImVec4(0.14f, 0.14f, 0.14f, 1.00f);
	colors[ImGuiCol_ScrollbarBg] = ImVec4(0.02f, 0.02f, 0.02f, 0.53f);
	colors[ImGuiCol_ScrollbarGrab] = ImVec4(0.31f, 0.31f, 0.31f, 1.00f);
	colors[ImGuiCol_ScrollbarGrabHovered] = ImVec4(0.41f, 0.41f, 0.41f, 1.00f);
	colors[ImGuiCol_ScrollbarGrabActive] = ImVec4(0.51f, 0.51f, 0.51f, 1.00f);
	colors[ImGuiCol_CheckMark] = ImVec4(1.00f, 1.00f, 1.00f, 1.00f);
	colors[ImGuiCol_SliderGrab] = ImVec4(0.34f, 0.34f, 0.34f, 1.00f);
	colors[ImGuiCol_SliderGrabActive] = ImVec4(0.39f, 0.38f, 0.38f, 1.00f);
	colors[ImGuiCol_Button] = ImVec4(0.41f, 0.41f, 0.41f, 0.74f);
	colors[ImGuiCol_ButtonHovered] = ImVec4(0.41f, 0.41f, 0.41f, 0.78f);
	colors[ImGuiCol_ButtonActive] = ImVec4(0.41f, 0.41f, 0.41f, 0.87f);
	colors[ImGuiCol_Header] = ImVec4(0.37f, 0.37f, 0.37f, 0.31f);
	colors[ImGuiCol_HeaderHovered] = ImVec4(0.38f, 0.38f, 0.38f, 0.37f);
	colors[ImGuiCol_HeaderActive] = ImVec4(0.37f, 0.37f, 0.37f, 0.51f);
	colors[ImGuiCol_Separator] = ImVec4(0.38f, 0.38f, 0.38f, 0.50f);
	colors[ImGuiCol_SeparatorHovered] = ImVec4(0.46f, 0.46f, 0.46f, 0.50f);
	colors[ImGuiCol_SeparatorActive] = ImVec4(0.46f, 0.46f, 0.46f, 0.64f);
	colors[ImGuiCol_ResizeGrip] = ImVec4(0.26f, 0.26f, 0.26f, 1.00f);
	colors[ImGuiCol_ResizeGripHovered] = ImVec4(0.31f, 0.31f, 0.31f, 1.00f);
	colors[ImGuiCol_ResizeGripActive] = ImVec4(0.35f, 0.35f, 0.35f, 1.00f);
	colors[ImGuiCol_Tab] = ImVec4(0.21f, 0.21f, 0.21f, 0.86f);
	colors[ImGuiCol_TabHovered] = ImVec4(0.27f, 0.27f, 0.27f, 0.86f);
	colors[ImGuiCol_TabActive] = ImVec4(0.34f, 0.34f, 0.34f, 0.86f);
	colors[ImGuiCol_TabUnfocused] = ImVec4(0.10f, 0.10f, 0.10f, 0.97f);
	colors[ImGuiCol_TabUnfocusedActive] = ImVec4(0.15f, 0.15f, 0.15f, 1.00f);
	colors[ImGuiCol_PlotLines] = ImVec4(0.61f, 0.61f, 0.61f, 1.00f);
	colors[ImGuiCol_PlotLinesHovered] = ImVec4(1.00f, 0.43f, 0.35f, 1.00f);
	colors[ImGuiCol_PlotHistogram] = ImVec4(0.90f, 0.70f, 0.00f, 1.00f);
	colors[ImGuiCol_PlotHistogramHovered] = ImVec4(1.00f, 0.60f, 0.00f, 1.00f);
	colors[ImGuiCol_TextSelectedBg] = ImVec4(0.26f, 0.59f, 0.98f, 0.35f);
	colors[ImGuiCol_DragDropTarget] = ImVec4(1.00f, 1.00f, 0.00f, 0.90f);
	colors[ImGuiCol_NavHighlight] = ImVec4(0.26f, 0.59f, 0.98f, 1.00f);
	colors[ImGuiCol_NavWindowingHighlight] = ImVec4(1.00f, 1.00f, 1.00f, 0.70f);
	colors[ImGuiCol_NavWindowingDimBg] = ImVec4(0.80f, 0.80f, 0.80f, 0.20f);
	colors[ImGuiCol_ModalWindowDimBg] = ImVec4(0.80f, 0.80f, 0.80f, 0.35f);

	if(setOnce)
		ImGui::SetNextWindowPos(ImVec2(menuPostion.x, menuPostion.y));
	ImGui::SetNextWindowSize(ImVec2(menuPostion.w, menuPostion.z));
	ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 0.f);
	if (ImGui::Begin("MainMenuListWindow", 0, ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize))
	{
		selctedMenuPostionUpdated.x = ImGui::GetWindowPos().x;
		selctedMenuPostionUpdated.y = ImGui::GetWindowPos().y;
		ImGui::BulletText("Main Menu");
		ImGui::Button("Local Options");
	}
	ImGui::PopStyleVar();
	ImGui::End();


	ImGui::SetNextWindowPos(ImVec2(selctedMenuPostion.x + selctedMenuPostionUpdated.x, selctedMenuPostion.y + selctedMenuPostionUpdated.y));
	ImGui::SetNextWindowSize(ImVec2(selctedMenuPostion.w, selctedMenuPostion.z));
	ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 0.f);
	if (ImGui::Begin("selctedMenuWindow", 0, ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoResize))
	{
		if (ImGui::ListBox("", &l_pickedModelSub, ModelSubNames, IM_ARRAYSIZE(ModelSubNames), 10))
		{
			l_CountForModels = 0;
			l_CountForModelsHash = -1;
			l_ModelLoaded = false;
			for (auto Model : PedModels)
			{
				if (Model.ID == l_pickedModelSub)
				{
					l_ModelNameArray[l_CountForModels] = StringToChar(Model.ModelName);
					l_CountForModels += 1;
					l_ModelHashArray[l_CountForModelsHash] = StringToChar(Model.ModelName);
					l_CountForModelsHash += 1;

				}

			}l_ModelLoaded = true;

		}ImGui::SameLine();
		if (l_ModelLoaded)
		{
			if (ImGui::ListBox("", &l_pickedModel, l_ModelNameArray, l_CountForModels, 10))
				std::cout<<(l_ModelHashArray[l_pickedModel]);
		}

	}
	ImGui::PopStyleVar();
	ImGui::End();
	setOnce = false;
}